// Wraps circom_tester so every test file resolves the wasm and include paths
// the same way.

import * as crypto from "crypto";
import * as fs from "fs";
import * as path from "path";
import { promisify } from "util";
import { exec as execCb } from "child_process";
// circom_tester ships without TS types
// @ts-ignore
import { wasm as wasmTester } from "circom_tester";

import type { Field, Point } from "../helpers";
import { ROOT } from "./files";

const SRC_DIR = path.join(ROOT, "src");
const NODE_MODULES = path.join(ROOT, "node_modules");

export const FIXTURES = path.join(ROOT, "test", "fixtures");

/**
 * A circom input object: signal name -> value, nested to the signal's arity.
 * The key set is part of the contract with the circuit; see `ref/witness.ts`.
 */
export type CircuitSignal = string | CircuitSignal[];
export type CircuitInput = Record<string, CircuitSignal>;

/**
 * Hand-written types for the subset of circom_tester's `wasm` tester this repo
 * uses.
 *
 * `calculateWitness` returns the flat witness vector: index 0 is the constant 1,
 * then the circuit outputs in declaration order, then everything else.
 */
export interface CircuitTester {
    calculateWitness(input: CircuitInput, sanityCheck?: boolean): Promise<bigint[]>;
    checkConstraints(witness: bigint[]): Promise<void>;
    assertOut(witness: bigint[], expected: Record<string, unknown>): Promise<void>;
}

/** Read output signal `index` out of a witness vector. */
export function readOutput(witness: bigint[], index = 0): Field {
    return witness[index + 1];
}

/** Read the point whose coordinates are outputs `index` and `index + 1`. */
export function readPoint(witness: bigint[], index = 0): Point {
    return [readOutput(witness, index), readOutput(witness, index + 1)];
}

export function srcPath(...parts: string[]): string {
    return path.join(SRC_DIR, ...parts);
}

export function fixturePath(name: string): string {
    return path.join(FIXTURES, name);
}

const GENERATED_FIXTURES = path.join(ROOT, "build", ".tester", "fixtures");

/**
 * A one-line wrapper `component main = <template>(<args>)` over `src/<source>`,
 * written under `build/` and returned as a path for `useCircuit`.
 *
 * Generated so the parameters stay in sync with `constants.ts`. The file is
 * rewritten only when its content changes, so the compile cache keyed on its
 * path stays valid.
 */
export function generatedFixture(source: string, template: string, args: readonly number[]): string {
    const name = `gen_${template}_${args.join("_")}.circom`;
    const file = path.join(GENERATED_FIXTURES, name);
    const include = path.relative(GENERATED_FIXTURES, path.join(SRC_DIR, source)).split(path.sep).join("/");
    const content = [
        "pragma circom 2.2.3;",
        "",
        `// Generated by test/lib/circuit.ts :: generatedFixture. Do not edit.`,
        `include "${include}";`,
        "",
        `component main = ${template}(${args.join(", ")});`,
        "",
    ].join("\n");
    fs.mkdirSync(GENERATED_FIXTURES, { recursive: true });
    if (!fs.existsSync(file) || fs.readFileSync(file, "utf8") !== content) {
        fs.writeFileSync(file, content);
    }
    return file;
}

// `wasmTester` compiles on every call; the cache holds one compile per circuit.
// Mocha runs without --parallel, so all spec files share one process and one
// cache. It is keyed on the absolute path and holds the promise, so concurrent
// `before` hooks for one circuit await a single compile.
//
// The output directory is pinned under `build/` (gitignored) because the
// compile also emits the `.r1cs` and `.sym` that `lib/r1cs.ts` reads.
const TESTER_OUT = path.join(ROOT, "build", ".tester");

const cache = new Map<string, Promise<CircuitArtifacts>>();

/**
 * A compiled circuit: the wasm tester plus the paths to its constraint system.
 * Both must come from the same compile: a stale `.r1cs` beside a fresh wasm
 * does not error.
 */
export interface CircuitArtifacts {
    tester: CircuitTester;
    /** `<name>.r1cs` — what a Groth16 proof binds. */
    r1csPath: string;
    /** `<name>.sym` — witness index -> signal name. */
    symPath: string;
}

/** Per-circuit output directory: basename plus a hash, so two fixtures that
 *  share a basename cannot collide. */
function outputDirFor(absPath: string): string {
    const tag = crypto.createHash("sha256").update(absPath).digest("hex").slice(0, 8);
    return path.join(TESTER_OUT, `${path.basename(absPath, ".circom")}-${tag}`);
}

/** Compile a circuit (once per process) and return its artifacts. */
export async function loadCircuitArtifacts(absPath: string): Promise<CircuitArtifacts> {
    let pending = cache.get(absPath);
    if (pending === undefined) {
        pending = (async () => {
            const output = outputDirFor(absPath);
            await fs.promises.mkdir(output, { recursive: true });
            const tester = (await wasmTester(absPath, {
                include: [NODE_MODULES],
                output,
            })) as CircuitTester;
            const base = path.basename(absPath, ".circom");
            return {
                tester,
                r1csPath: path.join(output, `${base}.r1cs`),
                symPath: path.join(output, `${base}.sym`),
            };
        })();
        cache.set(absPath, pending);
    }
    return pending;
}

export async function loadCircuit(absPath: string): Promise<CircuitTester> {
    return (await loadCircuitArtifacts(absPath)).tester;
}

// ===== unoptimized constraint systems =====

const exec = promisify(execCb);

/**
 * Compile a circuit to `.r1cs` and `.sym` only, with circom's optimizer off.
 *
 * `--O2` (circom's default, and the system a proof binds) substitutes linear
 * constraints away, including bit decompositions `sum 2^i b_i === in`, so a
 * structural search for decompositions needs the `--O0` system. The
 * substitutions preserve the solution set, so a decomposition wide enough to
 * alias at `--O0` also aliases at `--O2`.
 */
export async function compileConstraintsOnly(
    absPath: string,
): Promise<{ r1csPath: string; symPath: string }> {
    const base = path.basename(absPath, ".circom");
    const output = path.join(outputDirFor(absPath), "O0");
    const paths = {
        r1csPath: path.join(output, `${base}.r1cs`),
        symPath: path.join(output, `${base}.sym`),
    };

    let pending = o0Cache.get(absPath);
    if (pending === undefined) {
        pending = (async () => {
            await fs.promises.mkdir(output, { recursive: true });
            await exec(
                `circom ${JSON.stringify(absPath)} --r1cs --sym --O0 ` +
                    `-o ${JSON.stringify(output)} -l ${JSON.stringify(NODE_MODULES)}`,
            );
            return paths;
        })();
        o0Cache.set(absPath, pending);
    }
    return pending;
}

const o0Cache = new Map<string, Promise<{ r1csPath: string; symPath: string }>>();
